
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
spec:
  conversion:
    strategy: None
  group: etcd.database.coreos.com
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    plural: etcdclusters
    shortNames:
      - etcd
    singular: etcdcluster
  preserveUnknownFields: true
  scope: Namespaced
  version: v1beta2
  versions:
    - name: v1beta2
      served: true
      storage: true
