apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-controller-manager
  namespace: hugegraph-computer-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-etcd-operator
  namespace: hugegraph-computer-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-leader-election-role
  namespace: hugegraph-computer-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
- apiGroups:
  - hugegraph.baidu.com
  resources:
  - hugegraphcomputerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hugegraph.baidu.com
  resources:
  - hugegraphcomputerjobs/finalizers
  verbs:
  - update
- apiGroups:
  - hugegraph.baidu.com
  resources:
  - hugegraphcomputerjobs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-leader-election-rolebinding
  namespace: hugegraph-computer-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hugegraph-computer-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: hugegraph-computer-operator-controller-manager
  namespace: hugegraph-computer-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hugegraph-computer-operator-manager-role
subjects:
- kind: ServiceAccount
  name: hugegraph-computer-operator-controller-manager
  namespace: hugegraph-computer-operator-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator-etcd
    app.kubernetes.io/version: v1
    service.app: hugegraph-computer-operator-etcd
  name: hugegraph-computer-operator-etcd
  namespace: hugegraph-computer-operator-system
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app.kubernetes.io/name: hugegraph-computer-operator-etcd
    app.kubernetes.io/version: v1
    service.app: hugegraph-computer-operator-etcd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-controller-manager
  namespace: hugegraph-computer-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hugegraph-computer-operator
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hugegraph-computer-operator
        app.kubernetes.io/version: v1
    spec:
      containers:
      - args: []
        command:
        - java
        - -jar
        - hugegraph-computer-operator.jar
        env:
        - name: PROBE_PORT
          value: "9892"
        - name: WATCH_NAMESPACE
          value: hugegraph-computer-system
        - name: RECONCILER_COUNT
          value: "6"
        - name: INTERNAL_ETCD_URL
          value: http://hugegraph-computer-operator-etcd.hugegraph-computer-operator-system:2379
        - name: LOG_LEVEL
          value: INFO
        - name: AUTO_DESTROY_POD
          value: "true"
        image: hugegraph/hugegraph-computer-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 9892
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /ready
            port: 9892
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: hugegraph-computer-operator-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hugegraph-computer-operator-etcd
    app.kubernetes.io/version: v1
  name: hugegraph-computer-operator-etcd
  namespace: hugegraph-computer-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hugegraph-computer-operator-etcd
      app.kubernetes.io/version: v1
      service.app: hugegraph-computer-operator-etcd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hugegraph-computer-operator-etcd
        app.kubernetes.io/version: v1
        service.app: hugegraph-computer-operator-etcd
    spec:
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          HOSTNAME=$(hostname)
          etcd --name ${HOSTNAME} \
          --data-dir /var/etcd/data \
          --initial-advertise-peer-urls http://${HOSTNAME}.hugegraph-computer-operator-etcd.hugegraph-computer-operator-system:2380 \
          --listen-peer-urls http://0.0.0.0:2380 \
          --listen-client-urls http://0.0.0.0:2379 \
          --advertise-client-urls http://${HOSTNAME}.hugegraph-computer-operator-etcd.hugegraph-computer-operator-system:2379 \
          --initial-cluster ${HOSTNAME}=http://${HOSTNAME}.hugegraph-computer-operator-etcd.hugegraph-computer-operator-system:2380 \
          --initial-cluster-state new
        image: quay.io/coreos/etcd:v3.5.0
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl endpoint status
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: hugegraph-computer-operator-etcd
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl endpoint status
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
      hostname: hugegraph-computer-operator-etcd-0
      subdomain: hugegraph-computer-operator-etcd
