openapi: "3.0.0"
info:
paths:
components:
  schemas:
    # openAPIV3Schema
    spec:
      description: HugeGraphComputerJobSpec defines the desired state of HugeGraphComputerJob
      properties:
        algorithmName:
          type: string
        computerConf:
          additionalProperties:
            type: string
          type: object
        configMap:
          type: string
        envVars:
          additionalProperties:
            type: string
          type: object
        image:
          type: string
        jobId:
          type: string
        masterCpu:
          type: string
        masterMemory:
          type: string
        workerCpu:
          format: int32
          type: integer
        workerInstances:
          format: int32
          minimum: 1
          type: integer
        workerMemory:
          type: string
      type: object
    status:
      description: HugeGraphComputerJobStatus defines the observed state of HugeGraphComputerJob
      properties:
        jobStatus:
          type: string
      type: object
    # openAPIV3Schema


