# etcd operator doc: https://github.com/coreos/etcd-operator/tree/master/doc/user
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: etcd
  namespace: system
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  repository: quay.io/coreos/etcd
  size: 3
  version: "3.5.0"
