blank_issues_enabled: false

# 设置提 issue 前的参考文档
contact_links:
  - name: HugeGraph Computer Doc
    # TODO: fill it after release
    url: https://hugegraph.apache.org/docs/
    about: Please search question here before opening a new issue
  - name: HugeGraph API Doc
    url: https://hugegraph.apache.org/docs/clients/
    about: Please search usage here before opening a new issue
